//import fetch from 'cross-fetch'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'
export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGOUT = 'DO_LOGOUT'
export const GET_CURENT_PROJECT = 'GET_CURENT_PROJECT'
export const SET_PROJECT = 'SET_PROJECT'


//hook
export const NEW_PROJECT_COME = 'NEW_PROJECT_COME'
export const UPDATE_PROJECT_COME = 'UPDATE_PROJECT_COME'
export const REMOVE_PROJECT_COME = 'REMOVE_PROJECT_COMEs'
export const SET_TEAM = 'SET_TEAM'
export const LOAD_TEAM = 'LOAD_TEAM'

//sprint
export const SET_SPRINTS = 'SET_SPRINTS'
export const SET_MEMBERS='SET_MEMBERS'
export const SET_SPRINTBACKLOGS='SET_SPRINTBACKLOGS'

